/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.7/samples
 */
plugins {
  kotlin("jvm") version "1.9.22"
}

repositories {
  mavenCentral()
}

dependencies {
  // stdlib is added automatically by the plugin above
  implementation("org.junit.jupiter:junit-jupiter:5.10.0")
}

sourceSets {
  main {
      kotlin.setSrcDirs(listOf(".")) // Keep this so it finds your main.kt in root
  }
}

tasks.test {
  useJUnitPlatform()
}

